import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { createMapFileServer } = require('../scripts/map_file_server.js');
let server, base;
test.beforeAll(async () => {
    server = createMapFileServer({ repoRoot: path.resolve(import.meta.dirname, '..'), allowedHosts: '127.0.0.1' });
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
    base = `http://127.0.0.1:${server.address().port}`;
});
test.afterAll(async () => { await new Promise(resolve => server.close(resolve)); });

test('record, reorder, recover and download a journey; display it as an independent viewer layer', async ({ page }, testInfo) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', { value: undefined }));
    await page.goto(base + '/studio/editor');
    await expect(page.locator('#map-editor-app')).toHaveAttribute('data-loading', 'false');
    await page.locator('[data-map-id="main_continent"]').first().click();
    await page.locator('#editor-journeys-btn').click();
    await page.getByRole('button', { name: 'New journey', exact: true }).click();
    await page.getByLabel('Journey name', { exact: true }).fill('A road remembered');
    await page.getByLabel('Campaign', { exact: true }).fill('Test campaign');
    await page.getByLabel('Campaign wiki link', { exact: true }).fill('https://example.org/campaign');
    await page.locator('#editor-add-journey-stop-btn').click();
    await page.getByRole('button', { name: 'Cancel stop', exact: true }).click();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    const place = async (name, x, y) => {
        await page.locator('#editor-add-journey-stop-btn').click();
        await page.locator('#editor-map').click({ position: { x, y } });
        const row = page.locator('.journey-stop-editor').last();
        await row.getByLabel('Stop name', { exact: true }).fill(name);
        await row.getByLabel('In-universe date').fill('Late autumn, 58 BEC');
        await row.getByLabel('Stop wiki link').fill('https://example.org/arrival');
        await row.getByLabel('Stop wiki link').press('Tab');
    };
    await place('Arrival', 310, 270);
    await place('The crossing', 410, 340);
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await expect(page.locator('.campaign-journey-route')).toHaveCount(1);
    await page.locator('.journey-stop-editor').last().getByRole('button', { name: 'Move earlier' }).click();
    await expect(page.locator('.journey-stop-editor summary').first()).toContainText('The crossing');
    await page.locator('#editor-undo-btn').click();
    await expect(page.locator('.journey-stop-editor summary').first()).toContainText('Arrival');
    await page.locator('#editor-redo-btn').click();
    await expect(page.locator('.journey-stop-editor summary').first()).toContainText('The crossing');
    // Removal is reversible, and dragging a stop changes its downloaded position.
    await page.locator('.journey-stop-editor summary').first().click();
    await page.locator('.journey-stop-editor').first().getByRole('button', { name: 'Remove stop' }).click();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(1);
    await page.locator('#editor-undo-btn').click();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.locator('#editor-collapse-inspector-btn').click();
    const pin = page.locator('.campaign-journey-pin').first();
    const box = await pin.boundingBox();
    await page.mouse.move(box.x + 14, box.y + 14);
    await page.mouse.down();
    await page.mouse.move(box.x + 64, box.y + 34, { steps: 10 });
    await page.mouse.up();
    await expect(pin).toBeVisible();
    await expect.poll(async () => (await pin.boundingBox()).x).toBeGreaterThan(box.x + 30);
    await page.getByRole('button', { name: 'Edit details', exact: true }).click();
    await page.locator('[data-feature-section="journey"] > summary').click();
    await page.getByLabel('Show by default in viewer').check();
    await page.reload();
    await expect(page.locator('#map-editor-app')).toHaveAttribute('data-loading', 'false');
    await expect(page.locator('.journey-stop-editor summary').first()).toContainText('The crossing');
    await page.locator('[data-feature-section="journey"] > summary').click();
    await expect(page.getByLabel('Show by default in viewer')).toBeChecked();
    await page.getByLabel('Show by default in viewer').uncheck();
    await page.locator('[data-feature-section="journey"] > summary').click();
    const downloadEvent = page.waitForEvent('download');
    await page.locator('#save-current-map-btn').click();
    const download = await downloadEvent;
    const downloadPath = testInfo.outputPath('journey-map.json');
    await download.saveAs(downloadPath);
    const document = JSON.parse(fs.readFileSync(downloadPath, 'utf8'));
    expect(document.journeys[0].stops.map(stop => stop.name)).toEqual(['The crossing', 'Arrival']);
    expect(document.journeys[0].visibleByDefault).toBe(false);
    expect(document.journeys[0].stops[0].date).toBe('Late autumn, 58 BEC');
    const original = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, '../maps/Fair-Content.json'), 'utf8'));
    const { journeys, ...unchanged } = document;
    expect(unchanged).toEqual(original);
    await page.screenshot({ path: testInfo.outputPath('journey-editor-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('#editor-add-journey-stop-btn')).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    await page.screenshot({ path: testInfo.outputPath('journey-editor-mobile.png') });

    // Read the exported file through the real viewer without changing server files.
    await page.route('**/maps/Fair-Content.json*', route => route.fulfill({ json: document }));
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto(base + '/index.html#main_continent-s=c');
    await page.waitForFunction(() => typeof currentlyLoadedMapId !== 'undefined' && currentlyLoadedMapId === 'main_continent');
    await page.waitForFunction(() => !document.getElementById('loading-overlay') || getComputedStyle(document.getElementById('loading-overlay')).display === 'none');
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    await page.evaluate(() => { unlockAdvancedControls('test'); setMapBlurbVisible(false); });
    await page.locator('#toggle-filters-btn').click();
    await page.locator('.journey-filter').check();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await expect(page.locator('.campaign-journey-route')).toHaveAttribute('stroke-dasharray', '1 9');
    await page.evaluate(() => map.fitBounds(currentJourneyLayers.values().next().value.getBounds(), { paddingTopLeft: [370, 180], paddingBottomRight: [280, 300], maxZoom: -1, animate: false }));
    await page.locator('.campaign-journey-pin').first().click();
    await expect(page.locator('.journey-popup')).toContainText('Late autumn, 58 BEC');
    await expect(page.getByRole('link', { name: 'Read about this stop' })).toHaveAttribute('href', 'https://example.org/arrival');
    await expect(page.getByRole('link', { name: 'Open campaign wiki' })).toHaveAttribute('href', 'https://example.org/campaign');
    await page.screenshot({ path: testInfo.outputPath('journey-viewer-desktop.png') });
    await page.locator('#filter-journeys-all').uncheck();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    await page.locator('#filter-toggle-all').check();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.locator('#filter-toggle-all').uncheck();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    await page.locator('.journey-filter').check();
    await page.reload();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => isMobileLayoutActive);
    await expect(page.locator('#mobile-filters-btn')).toHaveJSProperty('hidden', false);
    await page.reload();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.waitForFunction(() => isMobileLayoutActive);
    await page.evaluate(() => { closeMobileSheet({ restoreFocus: false }); if (filtersPanelVisible) toggleFilterPanel(); });
    await page.locator('#mobile-tools-launcher-btn').click();
    await page.locator('#mobile-filters-btn').click();
    await page.locator('.journey-filter').uncheck();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    await page.locator('.journey-filter').check();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.screenshot({ path: testInfo.outputPath('journey-viewer-mobile.png') });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    expect(errors).toEqual([]);
});

test('default visibility, independent journeys, empty feature maps, and map switching', async ({ page }) => {
    const document = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, '../maps/Fair-Content.json'), 'utf8'));
    document.pointsOfInterest = [];
    document.regions = [];
    document.lines = [];
    document.roads = [];
    document.journeys = [
        { id: 'first', name: 'First trail', campaign: 'Campaign A', visibleByDefault: true, stops: [{ id: 'a', name: 'Camp', coords: [1000, 2000] }] },
        { id: 'second', name: 'Second trail', campaign: 'Campaign B', visibleByDefault: false, stops: [{ id: 'b', name: 'Port', coords: [2000, 3000] }] }
    ];
    await page.route('**/maps/Fair-Content.json*', route => route.fulfill({ json: document }));
    await page.goto(base + '/index.html#main_continent-s=c');
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(1);
    await page.evaluate(() => { unlockAdvancedControls('test'); setMapBlurbVisible(false); });
    await page.locator('#toggle-filters-btn').click();
    await expect(page.locator('#filter-journeys-all')).toHaveJSProperty('indeterminate', true);
    await expect(page.locator('#filter-toggle-all')).toHaveJSProperty('indeterminate', true);
    await page.locator('[data-journey-id="second"]').check();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(2);
    await page.locator('[data-journey-id="first"]').uncheck();
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(1);
    await expect(page.locator('.campaign-journey-pin')).toHaveAttribute('title', /Second trail/);
    await page.evaluate(() => loadMap('The-Port-City-of-Stomion'));
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(0);
    await expect(page.locator('.journey-filter')).toHaveCount(0);
    await page.evaluate(() => loadMap('main_continent'));
    await expect(page.locator('.campaign-journey-pin')).toHaveCount(1);
    await expect(page.locator('.campaign-journey-pin')).toHaveAttribute('title', /Second trail/);
});
