const assert = require('node:assert/strict');
const fs = require('node:fs');

const htmlSource = fs.readFileSync('map-editor.html', 'utf8');
const cssSource = fs.readFileSync('css/map-editor.css', 'utf8');
const leafletCssSource = fs.readFileSync('css/leaflet.css', 'utf8');
const jsSource = fs.readFileSync('js/map-editor.js', 'utf8');
const fieldsSource = fs.readFileSync('js/map-editor-fields.js', 'utf8');

assert.match(htmlSource, /id="editor-atlas-tree"/);
assert.match(htmlSource, /id="editor-library-title">Choose a map</);
assert.match(htmlSource, /id="editor-library-copy">Select a map to begin./);
assert.match(htmlSource, /id="map-editor-app" class="map-editor-shell" data-mode="library"[^>]+data-access="checking"[^>]+data-dirty="false"/);
assert.match(htmlSource, /id="editor-map-home"/);
assert.match(htmlSource, /id="editor-edit-map-details-btn"/);
assert.match(htmlSource, /id="editor-edit-points-btn"/);
assert.match(htmlSource, /id="editor-edit-regions-btn"/);
assert.match(htmlSource, /id="editor-edit-lines-btn"/);
assert.match(htmlSource, /id="editor-edit-map-advanced-btn"/);
assert.match(htmlSource, /id="editor-create-feature-btn"/);
assert.match(htmlSource, /id="editor-back-to-feature-list-btn"/);
assert.match(htmlSource, /id="editor-map"/);
assert.match(htmlSource, /id="map-settings-form"/);
assert.match(htmlSource, /data-map-field-surface="overview"/);
assert.match(htmlSource, /data-map-field-surface="advanced"/);
assert.match(htmlSource, /id="editor-feature-form"/);
assert.match(htmlSource, /id="save-current-map-btn"/);
assert.match(htmlSource, /id="save-atlas-structure-btn"/);
assert.match(htmlSource, /id="editor-save-state-chip"/);
assert.match(htmlSource, /id="editor-toggle-inspector-btn"/);
assert.match(htmlSource, /id="editor-inspector-resizer"/);
assert.match(htmlSource, /id="editor-undo-btn"/);
assert.match(htmlSource, /id="editor-redo-btn"/);
assert.match(htmlSource, /id="editor-tool-rail"/);
assert.match(htmlSource, /id="editor-inspector-launcher"[^>]+aria-label="Editing panels"/);
assert.match(htmlSource, /id="editor-inspector-launcher-toggle"[^>]+aria-label="Hide editing panel buttons"[^>]+aria-expanded="true"/);
assert.match(htmlSource, /id="editor-tool-select"[^>]+aria-keyshortcuts="V"/);
assert.match(htmlSource, /id="editor-tool-pan"[^>]+aria-keyshortcuts="H"/);
assert.match(htmlSource, /id="editor-tool-point"[^>]+aria-keyshortcuts="P"/);
assert.match(htmlSource, /id="editor-tool-region"[^>]+aria-keyshortcuts="R"/);
assert.match(htmlSource, /id="editor-tool-line"[^>]+aria-keyshortcuts="L"/);
assert.match(htmlSource, /id="editor-file-menu"[^>]+role="menu"/);
assert.match(htmlSource, /id="editor-edit-menu"[^>]+role="menu"/);
assert.match(htmlSource, /id="editor-view-menu"[^>]+role="menu"/);
assert.match(htmlSource, /id="editor-menu-save-btn"[^>]+data-menu-action="save"/);
assert.match(htmlSource, /id="editor-menu-inspector-btn"[^>]+data-menu-action="inspector"/);
assert.match(htmlSource, /id="editor-active-tool-label"/);
assert.match(htmlSource, /id="editor-zoom-status"[^>]+aria-label="Canvas zoom"/);
assert.match(htmlSource, /class="map-editor-inspector-chrome"/);
assert.match(htmlSource, /class="map-editor-inspector-collapse-icon"/);
assert.match(htmlSource, /class="map-editor-inspector-close-icon"/);
assert.match(htmlSource, /id="editor-current-map-id" class="map-editor-visually-hidden"/);
assert.match(htmlSource, /id="editor-export-readiness"/);
assert.match(htmlSource, /id="editor-export-btn"[^>]+aria-label="Export map data"[^>]+aria-controls="editor-export-dialog"/);
assert.match(htmlSource, /id="editor-export-dialog"/);
assert.match(htmlSource, /id="editor-export-build-preview-btn"/);
assert.match(htmlSource, /id="editor-preview-command-status"[^>]+data-state="blocked"/);
assert.match(htmlSource, /id="editor-undo-btn"[^>]+aria-label="Undo"[^>]*>\s*<span aria-hidden="true">↶<\/span>/);
assert.match(htmlSource, /id="editor-redo-btn"[^>]+aria-label="Redo"[^>]*>\s*<span aria-hidden="true">↷<\/span>/);
assert.match(htmlSource, /<strong>Hiraeth Map Studio<\/strong>\s*<span>Map Editor<\/span>/);
assert.match(htmlSource, /class="map-editor-library-tools">[\s\S]*id="editor-tree-search"[\s\S]*id="reload-editor-btn"[^>]*>Refresh maps<\/button>/m);
assert.match(htmlSource, /id="editor-unsaved-dialog"/);
assert.match(htmlSource, /Save and switch/);
assert.match(htmlSource, /id="editor-access-notice"[^>]+role="status"/);
assert.match(htmlSource, /id="editor-access-title">Checking editing access/);
assert.match(htmlSource, /id="editor-access-studio-link" href="\/studio"/);
assert.match(htmlSource, /id="editor-finish-draw-btn"[^>]*>Finish shape</);
assert.match(htmlSource, /id="editor-cancel-draw-btn"[^>]*>Cancel drawing</);
assert.doesNotMatch(htmlSource, />Finish Draft</);
assert.doesNotMatch(htmlSource, />Cancel Draft</);
assert.match(htmlSource, /js\/map-editor-history\.js/);
assert.match(htmlSource, /js\/map-editor-fields\.js/);
assert.match(htmlSource, /class="map-editor-appbar"/);
assert.match(htmlSource, /data-inspector-tab="overview"/);
assert.match(htmlSource, /data-inspector-tab="features"/);
assert.match(htmlSource, /data-inspector-tab="advanced"/);
assert.match(htmlSource, /class="map-editor-publish-panel"/);
assert.match(htmlSource, /class="map-editor-workspace"/);
assert.match(htmlSource, /id="editor-loading-title"/);
assert.match(htmlSource, /id="editor-loading-copy"/);
assert.match(htmlSource, /id="publish-readiness-title"/);
assert.match(htmlSource, /id="publish-readiness-summary"/);
assert.match(htmlSource, /id="publish-readiness-chip"/);
assert.match(htmlSource, /id="publish-build-progress"/);
assert.doesNotMatch(htmlSource, /id="publish-readiness-list"/);
assert.doesNotMatch(htmlSource, /id="publish-action-list"/);
assert.doesNotMatch(htmlSource, /id="publish-changed-file-groups"/);
assert.doesNotMatch(htmlSource, /id="publish-changed-files"/);
assert.doesNotMatch(htmlSource, /id="publish-warning-list"/);
assert.match(htmlSource, /id="build-live-preview-btn"/);
assert.match(htmlSource, /id="live-preview-link"/);
assert.match(htmlSource, /id="editor-preview-studio-link" href="\/studio">Details in Studio</);
assert.match(htmlSource, /id="export-current-map-btn"/);
assert.match(htmlSource, /id="export-atlas-structure-btn"/);
assert.match(htmlSource, /id="editor-map-empty-title"/);
assert.match(htmlSource, /id="editor-map-empty-copy"/);
assert.match(htmlSource, /id="editor-map-empty-detail"/);
assert.match(htmlSource, /id="map-editor-remote-notice"/);
assert.match(htmlSource, /This map editor only runs locally\./);
assert.match(htmlSource, /View the Maps/);
assert.match(htmlSource, /window\.__MAP_EDITOR_LOCAL_ACCESS__\s*=\s*isLocalAccess/);
assert.match(htmlSource, /hostname\.endsWith\("\.localhost"\)/);
assert.match(htmlSource, /if \(!window\.__MAP_EDITOR_LOCAL_ACCESS__\) return;/);
assert.match(htmlSource, /Drag POI markers to move them/);
assert.match(htmlSource, /css\/map-editor\.css/);
assert.match(htmlSource, /js\/map-editor\.js/);

assert.match(cssSource, /\.map-editor-shell\s*\{/);
assert.match(cssSource, /\.map-editor-shell \*,[\s\S]*box-sizing: border-box;/m);
assert.match(cssSource, /\.map-editor-shell\[data-mode="library"\] \.map-editor-sidebar\s*\{/);
assert.match(cssSource, /\[hidden\]\s*\{\s*display: none !important;/);
assert.match(cssSource, /\.map-editor-library-grid\s*\{/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="hub"\] \.map-editor-map-home\s*\{/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-browser"\] \.map-editor-inspector\s*\{/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-edit"\] \.map-editor-workspace,/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="hub"\] #editor-save-bar\[data-state="clean"\]/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="draw"\] #editor-save-bar\[data-state="clean"\]/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-browser"\] \.map-editor-panel-intro/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-edit"\] \.map-editor-inspector,[\s\S]*flex-direction: column;/m);
assert.match(cssSource, /--editor-ui-font:/);
assert.match(cssSource, /\.map-editor-form label input,[\s\S]*font-weight: 400;/m);
assert.match(cssSource, /\.map-editor-appbar\s*\{[\s\S]*--editor-wine|\.map-editor-appbar\s*\{[\s\S]*var\(--editor-wine\)/m);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-edit"\] \.map-editor-inspector-heading > button\s*\{\s*display: none;/);
assert.match(cssSource, /\.map-editor-save-bar\[data-state="locked"\] \.map-editor-primary-save\s*\{[\s\S]*display: none;/m);
assert.match(cssSource, /\.map-editor-shell\[data-access="writable"\] \.map-editor-access-notice\s*\{\s*display: none;/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="library"\]\[data-dirty="true"\] #editor-save-bar\s*\{\s*display: flex;/);
assert.match(cssSource, /\.map-editor-shell\[data-mode="library"\] #editor-map-home-btn:not\(\[hidden\]\)\s*\{\s*display: inline-flex;/);
assert.match(cssSource, /#editor-map-home-btn:not\(\[hidden\]\)::before\s*\{\s*content: "⌂";/);
assert.doesNotMatch(cssSource, /#editor-map-home-btn:not\(\[hidden\]\)::before\s*\{\s*content: "☰";/);
assert.match(cssSource, /@media \(max-width: 680px\)[\s\S]*\.map-editor-shell\[data-mode="feature-edit"\] \.map-editor-status,[\s\S]*display: none;/m);
assert.match(cssSource, /\.map-editor-empty-state\[hidden\]\s*\{\s*display: none;/);
assert.match(cssSource, /\.map-editor-shell\[data-loading="true"\] \.map-editor-workspace\s*\{[\s\S]*opacity:/m);
assert.doesNotMatch(cssSource, /\.map-editor-shell\[data-loading="true"\] \.map-editor-workspace\s*\{\s*display:\s*none;/m);
assert.match(cssSource, /\.map-editor-publish-panel\s*\{/);
assert.match(cssSource, /\.map-editor-workspace\s*\{/);
assert.match(cssSource, /\.map-editor-map-frame\s*\{[\s\S]*display: flex;/m);
assert.match(cssSource, /#editor-map\s*\{[\s\S]*min-height: 260px;[\s\S]*position: relative;[\s\S]*overflow: hidden;/m);
assert.match(cssSource, /\.map-editor-save-bar\s*\{/);
assert.match(cssSource, /\.map-editor-schema-fields\s*\{/);
assert.match(cssSource, /\.map-editor-inspector-resizer\s*\{/);
assert.match(cssSource, /@media \(max-width: 900px\)[\s\S]*\.map-editor-inspector\s*\{[\s\S]*position:\s*absolute;[\s\S]*box-shadow:/m);
assert.match(cssSource, /\.map-editor-inspector-tabs\s*\{/);
assert.match(cssSource, /\.map-editor-tree-list \.map-editor-tree-list\s*\{[\s\S]*margin-left: 14px;/m);
assert.match(cssSource, /\.map-editor-tree-group-header\s*\{/);
assert.match(cssSource, /#editor-map \.leaflet-map-pane \{ z-index: 100; \}/);
assert.match(cssSource, /#editor-map \.leaflet-image-layer \{[\s\S]*opacity: 1 !important;[\s\S]*visibility: visible !important;/m);
assert.match(cssSource, /\.map-editor-empty-detail\s*\{/);
assert.match(cssSource, /\.map-editor-detail-sections\s*\{/);
assert.match(cssSource, /\.map-editor-detail-section-row\s*\{/);
assert.match(cssSource, /\.map-editor-detail-section-add,/);
assert.match(cssSource, /\.map-editor-build-progress\s*\{/);
assert.match(cssSource, /\.map-editor-feature-section\s*\{/);
assert.match(cssSource, /\.editor-vertex-icon\s*\{/);
assert.match(cssSource, /--editor-chrome:/);
assert.match(cssSource, /\.map-editor-tool-rail\s*\{/);
assert.match(cssSource, /\.map-editor-tool-button\.active,/);
assert.match(cssSource, /\.map-editor-command-dialog\s*\{/);
assert.match(cssSource, /\.map-editor-top-menu-popover\s*\{/);
assert.match(cssSource, /\.map-editor-tool-button::after\s*\{/);
assert.match(cssSource, /\.map-editor-inspector-launcher-button\s*\{/);
assert.match(cssSource, /\.map-editor-inspector-launcher-button\.active\s*\{/);
assert.match(cssSource, /\.map-editor-inspector-launcher\[data-launcher-hidden="true"\]\s*\{/);
assert.match(cssSource, /\.map-editor-inspector-chrome\s*\{/);
assert.match(cssSource, /\.map-editor-canvas-status\s*\{/);
assert.match(cssSource, /\.map-editor-command-dialog-footer\s*\{/);
assert.match(cssSource, /Right-edge editing drawer[\s\S]*\.map-editor-shell\[data-mode="map-details"\] \.map-editor-workspace,[\s\S]*grid-template-columns: 46px minmax\(0, 1fr\);/m);
assert.match(cssSource, /\.map-editor-shell\[data-mode="feature-browser"\] \.map-editor-feature-controls select\s*\{\s*display: block;/);
assert.match(cssSource, /Workflow and accessibility corrections[\s\S]*grid-template-columns: auto minmax\(0, 1fr\) auto !important;/m);
assert.match(cssSource, /\.map-editor-inspector \.map-editor-feature-entry\s*\{[\s\S]*background: #fffdfa;/m);
assert.match(cssSource, /@media \(max-width: 680px\)[\s\S]*inset: 0 0 0 46px;[\s\S]*grid-template-columns: minmax\(0, 1fr\);/m);
assert.match(cssSource, /@media \(min-width: 901px\)[\s\S]*grid-template-columns: 46px minmax\(0, 1fr\) var\(--editor-inspector-width\) !important;[\s\S]*position: relative !important;/m);
assert.match(cssSource, /@media \(max-width: 680px\)[\s\S]*\.map-editor-shell\[data-mode="hub"\] \.map-editor-map-home-preview\s*\{[\s\S]*max-width: 100%;[\s\S]*aspect-ratio: auto;/m);
assert.match(cssSource, /Mobile canvases should fit the map[\s\S]*height: min\(70dvh, calc\(\(100vw - 46px\) \* 1\.25\)\) !important;/m);
assert.match(cssSource, /\.map-editor-shell\[data-mode="draw"\] \.map-editor-canvas-status \.map-editor-status\s*\{[\s\S]*text-overflow: clip;[\s\S]*white-space: normal;/m);
assert.match(leafletCssSource, /\.leaflet-touch \.leaflet-control-zoom a\s*\{\s*width: 44px;\s*height: 44px;\s*line-height: 44px;/m);

assert.match(jsSource, /beginDrawMode\('point'\)/);
assert.match(jsSource, /beginDrawMode\('region'\)/);
assert.match(jsSource, /beginDrawMode\('line'\)/);
assert.match(jsSource, /getCurrentMapDataUrl/);
assert.match(jsSource, /currentMapDataUrl/);
assert.match(jsSource, /saveCurrentMapJson/);
assert.match(jsSource, /saveAtlasStructure/);
assert.match(jsSource, /buildLivePreview/);
assert.match(jsSource, /applyServerReadiness/);
assert.match(jsSource, /markCurrentMapDirty/);
assert.match(jsSource, /editorDirty/);
assert.match(jsSource, /Editor changes saved/);
assert.match(jsSource, /\/api\/editor\/status/);
assert.match(jsSource, /\/api\/editor\/build-preview/);
assert.match(jsSource, /\/api\/editor\/build-preview-status/);
assert.match(jsSource, /\/api\/editor\/save-atlas/);
assert.match(jsSource, /\/api\/editor\/save-workspace/);
assert.match(fieldsSource, /map\?\.dataUrl \|\| context\.currentMapDataUrl/);
assert.match(jsSource, /refreshSaveControls/);
assert.match(jsSource, /setInspectorCollapsed/);
assert.match(jsSource, /registerInspectorResize/);
assert.match(jsSource, /registerInspectorTabs/);
assert.match(jsSource, /function setInspectorLauncherHidden\(hidden, persist = true\)/);
assert.match(jsSource, /localStorage\.setItem\('mapEditorLauncherHidden'/);
assert.match(jsSource, /setInspectorTab/);
assert.match(jsSource, /checkpointHistory/);
assert.match(jsSource, /undoEditorChange/);
assert.match(jsSource, /redoEditorChange/);
assert.match(jsSource, /requestMapSelection/);
assert.match(jsSource, /beforeunload/);
assert.match(jsSource, /const reviewOnlyRequested = editorSearchParams\.get\('mode'\) === 'review'/);
assert.match(jsSource, /function canMutateWorkspace\(\)/);
assert.match(jsSource, /function syncEditingAvailability\(\)/);
assert.match(jsSource, /button\.title = \[item\.name/);
assert.match(htmlSource, /class="dm-library-options"/);
assert.match(jsSource, /tile\.className = 'dm-new-map-tile'/);
assert.match(jsSource, /form\.querySelectorAll\('input, textarea, select, button'\)/);
assert.match(jsSource, /function hasUnfinishedGeometryDraft\(\)/);
assert.match(jsSource, /function hasUnsavedEditorWork\(\)/);
assert.match(jsSource, /dom\.appShell\.dataset\.dirty = String\(hasUnsavedEditorWork\(\)\)/);
assert.match(jsSource, /function requestExternalNavigation\(url\)/);
assert.match(jsSource, /function openUnsavedTransition\(transition\)/);
assert.match(jsSource, /exportCurrentMapJson/);
assert.match(jsSource, /exportAtlasStructure/);
assert.match(jsSource, /getMapContainerSize/);
assert.match(jsSource, /queueMapViewportReset/);
assert.match(jsSource, /fitBounds\(state\.currentBounds, \{ padding: \[10, 10\], animate: false \}\)/);
assert.match(jsSource, /setLoadingStage\('Loading atlas index'/);
assert.match(jsSource, /scheduleMapLayerRender/);
assert.match(jsSource, /function setWorkflowMode\(mode\)/);
assert.match(jsSource, /dom\.workspace\.scrollTop = 0/);
assert.match(jsSource, /dom\.inspector\.scrollTop = 0/);
assert.match(jsSource, /function openFeatureBrowser\(type\)/);
assert.match(jsSource, /libraryReturnMode: 'hub'/);
assert.match(jsSource, /const canOpenMapMenu = Boolean/);
assert.match(jsSource, /state\.selectedFeature\?\.mode !== 'points'/);
assert.match(jsSource, /dom\.appShell\.dataset\.mode === 'draw'/);
assert.match(jsSource, /Drag the selected marker to update its position\./);
assert.match(jsSource, /Drag the marker to reposition\./);
assert.match(jsSource, /Drag the orange handles to reshape\./);
assert.match(jsSource, /button\.dataset\.mapId = item\.id/);
assert.match(jsSource, /openMode: requestedMapId \? 'hub' : 'library'/);
assert.match(jsSource, /function getWorkspaceFingerprint\(\)/);
assert.match(jsSource, /function recordSavedWorkspaceBaseline\(options = \{\}\)/);
assert.match(jsSource, /function reconcileCurrentMapDirty\(detail = 'Editor changes restored\.'\)/);
assert.match(jsSource, /reconcileCurrentMapDirty\(actionLabel\)/);
assert.match(jsSource, /const requiredDraftPoints = state\.drawMode === 'region' \? 3/);
assert.match(jsSource, /dom\.finishDrawButton\.disabled = !canMutateWorkspace\(\) \|\| !state\.drawMode \|\| remainingDraftPoints > 0/);
assert.match(jsSource, /dom\.appShell\.dataset\.mode !== 'library'/);
assert.match(jsSource, /function setActiveTool\(tool, options = \{\}\)/);
assert.match(jsSource, /state\.map\.dragging\.enable\(\)/);
assert.match(jsSource, /openExportDialog/);
assert.match(jsSource, /function openAppMenu\(menuName, focusPosition = ''\)/);
assert.match(jsSource, /function runAppMenuAction\(action\)/);
assert.match(jsSource, /function refreshAppMenuState\(\)/);
assert.match(jsSource, /function updateZoomStatus\(\)/);
assert.match(jsSource, /const tool = \{ v: 'select', h: 'pan', p: 'point', r: 'region', l: 'line' \}\[shortcut\]/);
assert.match(jsSource, /storedCollapsed = localStorage\.getItem\('mapEditorDrawerCollapsed'\)/);
assert.match(jsSource, /setInspectorCollapsed\(storedCollapsed === null \? true : storedCollapsed === 'true', false\)/);
assert.match(jsSource, /dom\.focusTitle\.textContent = canMutateWorkspace\(\) \? 'Map & Scale' : 'Review map & scale'/);
assert.match(jsSource, /dom\.focusTitle\.textContent = canMutateWorkspace\(\) \? 'Advanced setup' : 'Review map setup'/);
assert.match(jsSource, /state\.map\.setView\(\[0, 0\], 0, \{ animate: false \}\)/);
assert.match(jsSource, /minZoom:\s*-6,/);
assert.match(jsSource, /zoomSnap:\s*0,/);
assert.match(jsSource, /moveNodeInTree/);
assert.match(jsSource, /renderFeatureInspector/);
assert.match(jsSource, /renderPointFeatureInspector/);
assert.match(jsSource, /renderRegionFeatureInspector/);
assert.match(jsSource, /renderLineFeatureInspector/);
assert.match(jsSource, /fieldApi\.renderFeatureFields/);
assert.match(jsSource, /fieldApi\.readMapForm/);
assert.match(jsSource, /getMapSettingsFieldValues/);
assert.match(jsSource, /setMapSettingsFieldValues/);
assert.match(jsSource, /renderMapParentOptions/);
assert.match(jsSource, /renderMapSettingsForm/);
assert.match(jsSource, /data-detail-section-list/);
assert.match(jsSource, /data-detail-section-field="heading"/);
assert.match(jsSource, /data-detail-section-field="body"/);
assert.match(fieldsSource, /key: 'propertiesText'/);
assert.match(fieldsSource, /key: 'detailSections'/);
assert.match(fieldsSource, /dataset\.action = 'add-detail-section'/);
assert.match(fieldsSource, /key: 'tags'/);
assert.match(fieldsSource, /Advanced properties JSON/);
assert.match(fieldsSource, /registerMapField/);
assert.match(fieldsSource, /registerFeatureField/);
assert.match(jsSource, /parseKeyFacts/);
assert.match(jsSource, /parseDetailSections/);
assert.match(jsSource, /getDetailSectionsFromForm/);
assert.match(jsSource, /renderDetailSectionControls/);
assert.match(jsSource, /parseTags/);
assert.match(jsSource, /getPointMarkerAccessibleName/);
assert.match(jsSource, /name: '',\s*coords: coordinate,\s*type: ''/);
assert.match(jsSource, /function getIncompleteFeature\(\)/);
assert.match(jsSource, /Give the new feature an intentional name before saving/);
assert.match(jsSource, /dom\.exportOpenPreviewLink\.hidden = !previewReady/);
assert.match(jsSource, /function invalidateLivePreview\(\)/);
assert.match(jsSource, /bundle\.stale \|\| hasUnsavedEditorWork\(\)/);
assert.match(jsSource, /dom\.livePreviewLink\.setAttribute\('aria-disabled', String\(!previewReady\)\)/);
assert.match(jsSource, /previewStudioLink: document\.getElementById\('editor-preview-studio-link'\)/);
assert.match(jsSource, /dom\.accessStudioLink, dom\.previewStudioLink/);
assert.match(jsSource, /RECOVERY_VERSION = 2/);
assert.match(jsSource, /RECOVERY_MAX_BYTES = 1500000/);
assert.match(jsSource, /window\.sessionStorage\.setItem\(storageKey, serialized\)/);
assert.match(jsSource, /state\.recoveryBaselineHash = hashRecoveryValue\(recoveryBaseline\)/);
assert.match(jsSource, /state\.recoveryBaselineLength = recoveryBaseline\.length/);
assert.match(jsSource, /JSON\.stringify\(stableJsonValue\(\{ mapDocument, atlasDocument \}\)\)/);
assert.match(jsSource, /snapshot\.baselineHash === state\.recoveryBaselineHash/);
assert.match(jsSource, /snapshot\.baselineLength === state\.recoveryBaselineLength/);
assert.match(jsSource, /workspace\?\.draft\?\.id \|\| workspace\?\.draft\?\.branch/);
assert.match(jsSource, /await accessPromise;\s*restoreRecoverySnapshot\(\);/);
assert.match(jsSource, /drawMode: hasUnfinishedGeometryDraft\(\) \? state\.drawMode : ''/);
assert.match(jsSource, /draftCoordinates: hasUnfinishedGeometryDraft\(\) \? utils\.cloneJson\(state\.draftCoordinates\) : \[\]/);
assert.match(jsSource, /state\.draftCoordinates\.push\(coordinate\);[\s\S]*markGeometryDraftUnsaved\(\);/m);
assert.match(jsSource, /restoreSavedWorkspaceBaseline\(\);\s*closeUnsavedDialog\(\);/);
assert.match(jsSource, /if \(selectionRequestId !== state\.mapSelectionRequestId\) return false;/);
assert.match(jsSource, /resolvedMap = \{ \.\.\.resolvedMap, dataUrl: resolvedDataUrl \}/);
assert.match(jsSource, /function flushSelectedFeatureForm\(\)/);
assert.match(jsSource, /syncEditingAvailability\(\);\s*refreshSaveControls\(\);\s*try \{/);
assert.match(jsSource, /async function saveAtlasStructure\(\)[\s\S]*state\.saveInProgress = true;[\s\S]*syncEditingAvailability\(\);[\s\S]*finally \{\s*state\.saveInProgress = false;\s*syncEditingAvailability\(\);/m);
assert.match(jsSource, /debouncedRenderSelectedFeatureUpdate/);
assert.doesNotMatch(jsSource, /debouncedUpdateSelectedFeatureFromForm/);
assert.match(cssSource, /Critical mobile actions keep a full touch target[\s\S]*min-height: 44px !important;/m);
assert.match(jsSource, /title:\s*markerLabel,\s*alt:\s*markerLabel/);
assert.match(jsSource, /setMapEmptyState/);
assert.match(jsSource, /getMapPresetGroupLabel/);
assert.match(jsSource, /imageLayer\.once\('load'/);
assert.match(jsSource, /imageLayer\.once\('error'/);
assert.doesNotMatch(jsSource, /Save this map before publishing\./);

console.log('map-editor shell regression checks passed');
