const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'map-studio.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'js/map-studio.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css/map-studio.css'), 'utf8');

assert.match(html, /js\/map-studio-model\.js/);
assert.match(html, /class="pipeline-steps"/);
assert.match(html, /id="pipeline-details"[^>]+class="studio-pipeline"/);
assert.match(html, /id="pipeline-summary-status"/);
assert.match(html, /id="continue-editing-link"/);
assert.match(html, /id="workflow-pull-request-link"/);
assert.match(html, /id="studio-editor-link"[^>]+mode=review/);
assert.match(html, /id="studio-preview-link"[^>]+aria-disabled="true"/);
assert.match(html, /id="open-editor-link"[^>]+mode=review/);
assert.match(html, /id="workspace-capability-note"/);
assert.match(html, /id="abandon-draft-dialog"/);
assert.match(html, /id="abandon-draft-confirmation"/);
assert.match(html, /id="github-setup-details"/);
assert.match(html, /id="check-github-button"/);
assert.match(html, /id="new-map-preview-image"/);
assert.match(html, /id="new-map-plan-files"/);
assert.match(html, /data-new-map-step="1"/);
assert.match(html, /data-new-map-step="4"/);
assert.match(html, /id="new-map-next-button"/);
assert.match(html, /id="new-map-back-button"/);
assert.match(html, /Advanced scale calibration/);
assert.match(html, /pattern="\[a-z0-9\]\(\?:\[a-z0-9\]\|-\)\*"/);
assert.match(html, /id="review-new-map-button"/);
assert.match(html, /id="resume-publish-button"/);
assert.match(html, /id="dismiss-publish-button"/);
assert.ok(
    html.indexOf('class="review-shortcut"') < html.indexOf('class="studio-card workflow-card"'),
    'safe review shortcut should appear before draft workflow content'
);
assert.match(html, /id="draft-title"[^>]+aria-describedby="draft-title-help"[^>]+required/);
assert.match(html, /id="start-draft-button"[^>]+aria-describedby="draft-title-help"[^>]+disabled/);
assert.match(script, /deriveWorkspacePresentation/);
assert.match(script, /payload\.authenticationRequired === false/);
assert.match(script, /capabilities\??\.canCreateMap/);
assert.match(html, /\/studio\/editor\?mode=review/);
assert.match(script, /publishJob\?\.status === 'complete'/);
assert.match(script, /\.toLowerCase\(\)/);
assert.match(script, /function formatFileSize/);
assert.match(script, /function setNewMapStep/);
assert.match(script, /\/api\/studio\/drafts\/abandon/);
assert.match(script, /confirmBranch/);
assert.match(script, /\/api\/studio\/github\/check/);
assert.match(script, /setup\.remediation/);
assert.match(script, /\/api\/studio\/maps\/plan/);
assert.match(script, /getNewMapPlanSignature/);
assert.match(script, /\/api\/studio\/publish\/resume/);
assert.match(script, /\/api\/studio\/publish\/dismiss/);
assert.match(script, /function updateStartDraftAvailability\(\)/);
assert.match(script, /workspace\?\.capabilities\?\.canStartDraft === true/);
assert.match(script, /dom\.draftTitle\.addEventListener\('input'/);
assert.match(script, /dom\.publishButton\.hidden = !presentation\.activeDraft/);
assert.match(html, /id="studio-publication-panel"/);
assert.match(html, /id="edit-maps-button"/);
assert.match(css, /\.studio-appbar\s*\{/);
assert.match(css, /\.pipeline-steps\s*\{/);
assert.match(css, /\.confirmation-form\s*\{/);
assert.match(css, /\.github-setup-details\s*\{/);
assert.match(css, /\.new-map-artwork-preview/);
assert.match(css, /\.new-map-plan\s*\{/);
assert.match(css, /\.new-map-scroll-region\s*\{/);
assert.match(css, /\.dialog-footer\s*\{/);
assert.match(css, /\.new-map-advanced\s*\{/);
assert.match(css, /\.availability-note\s*\{[^}]*grid-column:\s*1\s*\/\s*-1/s);
assert.match(css, /\.studio-pipeline\s*>\s*summary\s*\{/);
assert.match(css, /\.workflow-actions button:disabled/);

console.log('map studio shell checks passed');
