const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'map-studio.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'js/map-studio.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'css/map-studio.css'), 'utf8');

assert.match(html, /js\/map-studio-model\.js/);
assert.match(html, /class="pipeline-steps"/);
assert.match(html, /id="continue-editing-link"/);
assert.match(html, /id="workspace-capability-note"/);
assert.match(html, /id="abandon-draft-dialog"/);
assert.match(html, /id="abandon-draft-confirmation"/);
assert.match(html, /id="github-setup-details"/);
assert.match(html, /id="check-github-button"/);
assert.match(html, /id="new-map-preview-image"/);
assert.match(html, /id="new-map-plan-files"/);
assert.match(html, /id="review-new-map-button"/);
assert.match(html, /id="resume-publish-button"/);
assert.match(html, /id="dismiss-publish-button"/);
assert.match(script, /deriveWorkspacePresentation/);
assert.match(script, /capabilities\.canCreateMap/);
assert.match(script, /\/api\/studio\/drafts\/abandon/);
assert.match(script, /confirmBranch/);
assert.match(script, /\/api\/studio\/github\/check/);
assert.match(script, /setup\.remediation/);
assert.match(script, /\/api\/studio\/maps\/plan/);
assert.match(script, /getNewMapPlanSignature/);
assert.match(script, /\/api\/studio\/publish\/resume/);
assert.match(script, /\/api\/studio\/publish\/dismiss/);
assert.match(css, /\.studio-appbar\s*\{/);
assert.match(css, /\.pipeline-steps\s*\{/);
assert.match(css, /\.confirmation-form\s*\{/);
assert.match(css, /\.github-setup-details\s*\{/);
assert.match(css, /\.new-map-artwork-preview/);
assert.match(css, /\.new-map-plan\s*\{/);

console.log('map studio shell checks passed');
